<a href="https://colab.research.google.com/github/Chilakalapudisharon/BT-2026/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Introduction to Pandas**

Pandas is an open-source software library written for the Python programming language, primarily used for data manipulation and analysis. It provides powerful and flexible data structures designed to make working with tabular and time-series data both easy and intuitive.

**Key features and functionalities of Pandas include: Data Structures:**

Pandas introduces two primary data structures:

**Series:** A one-dimensional labeled array capable of holding any data type. It can be thought of as a single column in a spreadsheet.

**DataFrame:** A two-dimensional labeled data structure with columns of potentially different data types. It is similar to a spreadsheet or SQL table, providing a powerful way to represent and manipulate tabular data.

**what is pandas used for?**

pandas is used throughout the data analysis workflow. With pandas, you can:

   1.Import datasets from databases, spreadsheets, comma-separated values (CSV) files, and more.
   2.Clean datasets, for example, by dealing with missing values.
   3.Tidy datasets by reshaping their structure into a suitable format for analysis.
   4.Aggregate data by calculating summary statistics such as the mean of columns, correlation between them, and more.
   5.Visualize datasets and uncover insights.

**Importing data in pandas**

In [1]:
import pandas as pd

**Importing CSV files**

Use **read_csv() **with the path to the CSV file to read a comma-separated values file

In [9]:
df=pd.read_excel("/content/Student details.xlsx")

In [10]:
df.head()

,Unnamed: 0,Student Name,Roll no,Branch,Subjects,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,0,NaN,NaN,NaN,Java,Python,Physics,Chemistry,Maths
1,1,Ramya,1.0,CSM,80,99,65,89,70
2,2,Lohitha,2.0,CSE,88,78,78,80,68
3,3,Shravya,4.0,CSO,85,90,98,54,90
4,4,Rahul,5.0,CSD,59,89,60,90,80

In [11]:
df.tail()

,Unnamed: 0,Student Name,Roll no,Branch,Subjects,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
6,6,Navya,3.0,IOT,98,47,89,95,68
7,7,Sai,9.0,MECH,45,87,70,97,90
8,8,Gayathri,10.0,CIVIL,70,85,87,84,89
9,9,Raju,22.0,CSE,83,67,69,78,79
10,10,Ram Tej,45.0,CSM,98,90,92,99,97

In [12]:
df.describe()

       Unnamed: 0    Roll no
count   11.000000  10.000000
mean     5.000000  10.700000
std      3.316625  13.482911
min      0.000000   1.000000
25%      2.500000   3.250000
50%      5.000000   5.500000
75%      7.500000   9.750000
max     10.000000  45.000000

In [13]:
df.columns

Index(['Unnamed: 0', 'Student Name', 'Roll no', 'Branch', 'Subjects',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7'],
      dtype='object')

**Importing text files**

In [17]:
df2=pd.read_excel("content//Student details.xlsx")

In [18]:
df2

,Unnamed: 0,Student Name,Roll no,Branch,Subjects,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,0,NaN,NaN,NaN,Java,Python,Physics,Chemistry,Maths
1,1,Ramya,1.0,CSM,80,99,65,89,70
2,2,Lohitha,2.0,CSE,88,78,78,80,68
3,3,Shravya,4.0,CSO,85,90,98,54,90
4,4,Rahul,5.0,CSD,59,89,60,90,80
5,5,Sharma,6.0,CSO,67,65,56,99,67
6,6,Navya,3.0,IOT,98,47,89,95,68
7,7,Sai,9.0,MECH,45,87,70,97,90
8,8,Gayathri,10.0,CIVIL,70,85,87,84,89
9,9,Raju,22.0,CSE,83,67,69,78,79
10,10,Ram Tej,45.0,CSM,98,90,92,99,97

In [19]:
df2.describe()

       Unnamed: 0    Roll no
count   11.000000  10.000000
mean     5.000000  10.700000
std      3.316625  13.482911
min      0.000000   1.000000
25%      2.500000   3.250000
50%      5.000000   5.500000
75%      7.500000   9.750000
max     10.000000  45.000000

In [20]:
df3=pd.read_excel("/content/Student details.xlsx")

In [21]:
df3.head()

,Unnamed: 0,Student Name,Roll no,Branch,Subjects,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,0,NaN,NaN,NaN,Java,Python,Physics,Chemistry,Maths
1,1,Ramya,1.0,CSM,80,99,65,89,70
2,2,Lohitha,2.0,CSE,88,78,78,80,68
3,3,Shravya,4.0,CSO,85,90,98,54,90
4,4,Rahul,5.0,CSD,59,89,60,90,80